services:
  site:
    build: .
    image: hugo-arch
    command: hugo server -D --bind 0.0.0.0 --baseURL http://localhost:1313/
    volumes:
      - .:/site
    working_dir: /site
    ports:
      - "1313:1313"
    tty: true
